### ISSUE TITLE
Is all the patching in ldm/modules/encoders/modules.py actually necessary?

### ISSUE THREAD

**Issue by zwishenzug** [rinongal/textual_inversion#100]
This is more of a discussion than a bug/feature request.

I've been using this repository and the AUTOMATIC1111 repository as references to implement textual inversion into my local version.

In your repository there's a lot of code to patch up the FrozenCLIPEmbedder, it seems that it's so that you can pass around your embeddings manager, but can't this be done a lot more simply as in the AUTOMATIC1111 version, by just replacing the CLIPTextEmbeddings.token_embedding object?

For example, in my local version, after creating the model, I just monkey patch it like this:

    model_embeddings = model.cond_stage_model.transformer.text_model.embeddings
    model_embeddings.token_embedding = EmbeddingsWithFixes(model_embeddings.token_embedding, fixes)
	
fixes here could be your embeddings manager instead, in my case it's just a list of token id's and the replacement embeddings.

Then this class is used where I just look for the token_ids I'm interested in and replace the embeddings.  My code for this is a bit ugly, but I think you get the point.

    class EmbeddingsWithFixes(torch.nn.Module):
        def __init__(self, wrapped, fixes):
            super().__init__()
            self.wrapped = wrapped
            self.fixes = fixes

        def forward(self, input_ids):
            inputs_embeds = self.wrapped(input_ids)

            vecs_j = []
            for j in range(len(input_ids)):
                vecs_i = []
                for i in range(len(input_ids[j])):
                    v = inputs_embeds[j][i]
                    for fix in self.fixes:
                        if input_ids[j][i] == fix.token_id:
                            v = fix.data
                    vecs_i.append(v)
                vecs_j.append(torch.stack(vecs_i))

            return torch.stack(vecs_j)

Instead of storing fixes in the object, you could store embedding_manager and then just do your bit like this:

                if self.embedding_manager is not None:
                    inputs_embeds = self.embedding_manager(input_ids, inputs_embeds)

instead of my hacky loops.

Hope that makes some sense, it seems to be a much simpler way of doing this.

**Comment by rinongal** [comment]
You can absolutely do something like that, yes. 

I actually had something similar to begin with (which you can see in messy commented out code [here](https://github.com/rinongal/textual_inversion/blob/main/ldm/modules/encoders/modules_bak.py) because I forgot to remove the backup file from the released version 😄) but I swapped to the current version over some debugging concerns.

Didn't see a compelling reason to swap back.

**Comment by rinongal** [comment]
I'm guessing this is resolved, so I'll close it for now. Let me know if you need more help.
