### ISSUE TITLE
init_word and initializer_words arguments understanding

### ISSUE THREAD

**Issue by SoyGema** [rinongal/textual_inversion#101]
Hello there!
Congratulations on the release of this work and the steps towards creative content generation with Textual Inversion! 🥇 
I do have a conceptual question regarding the overall difference in between two arguments and their relationship with the paper and docs :

- **init_word**  I understand this parameter as an initialization embedding for S* in order to be optimized . According to the docs if you put more than one word in this setup it will only take the first one. Is this assumption correct ?

- **initializer_words** allows us to put more than one word and matches the 5.2 Evaluation setups **Extended latent spaces** section, is this correct ? Where can we found it in the code ? I have found [this](https://github.com/rinongal/textual_inversion/blob/4020ea755ca2bbe01218f32765ddfc60dd779340/ldm/modules/embedding_manager.py#L74) which seems to be related to init_word approach but not initializer_words

If you could please point me out in the right direction about how to **ensure** I´m using the extended latent spaces on this (using various words) Ill be very grateful

Thanks for the time dedicated to this issue, have a nice day!

**Comment by rinongal** [comment]
`init_word` is just a quick way to overwrite the first item in the `initializer_words` list.
The only way in which more than one initializer word will be used, is if you define multiple placeholder tokens for your training run (in which case, each of them will get initialized using the word in the same index).

The extended latent spaces experiment is just using num_vectors_per_token > 1. If you do that, **all** the vectors matching each token will be assigned the same initialization. It will **not** use a different word for each token.

**Comment by rinongal** [comment]
This seems resolved so I'm going to close it. Feel free to reopen if you need further help with this.
