### ISSUE TITLE
What are the recommended max training steps and number of images?

### ISSUE THREAD

**Issue by watermelon-juice-maker** [rinongal/textual_inversion#117]
Hi team,

I have been experimenting textual inversion with stable diffusion for few days. I am training it to draw different body types. 

What I have found is I am getting pretty good results with 10-15 images before flipping them and 10k training steps. However, after training more than 20 images, strangely, I am not getting any good results. Then I train it with 20k, 50k, 70k and 80k steps. Some outputs are ok but not as good as 10 images with 10k steps.

I am not sure what parameters should I use to get good results. In addition, if I want to train a specific area on body, for example hands, arms and thighs. Should I crop the image and train images with only hands, arms and thighs or I should train images with full body?

Thank you for your help!

**Comment by rinongal** [comment]
Hi! Sorry, completely missed this. For specific objects with LDM, our experiments tended to give better results for smaller sets (~5 varied images). If you want to learn a very broad concept (for example 'cat face images' and not a specific cat) then you can use larger sets (50+ images) and increase the training step count to get better results.

We did not investigate this in SD, or check how this is affected when you train with more than 1 token (which should help improve quality if you're only interested in learning a concept and not aiming to later change styles).

About your setup - are you trying to generate the objects separately, or all together? If it's separately, then you'll want to train on cropped images which highlight the specific part, yes.

**Comment by watermelon-juice-maker** [comment]
Thanks for the reply, much appreciated. I will try to use smaller sets with more token.
