### ISSUE TITLE
Disable flip augmentation?

### ISSUE THREAD

**Issue by LexCybermac** [rinongal/textual_inversion#13]
I understand in the vast majority of cases there is a tremendous advantage to augmenting data by flipping it, however in my particular case I have a large and well varied dataset comprised of very strictly asymmetrical data and I worry that the flipping might be hurting the training process from resolving as well as it ought to be.

I will stress I'm not expecting a flag or such to be implemented for my admittedly very much edge-case use, however a quick pointer as to what files I need to look at and roughly where to disable the flip process would be very much appreciated.

**Comment by rinongal** [comment]
The file you're interested in is here: ldm/data/personalized.py (flip runs at line 157 so you can comment it out if you want).

But you can actually change it (and other data parameters) through the conifg already!

If you look at the finetuning config files, you'll see this block:

```data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    wrap: false
    train:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512
        set: train
        per_image_tokens: false
        repeats: 100
    validation:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512
        set: val
        per_image_tokens: false
        repeats: 10
```

The internal train/validation blocks (which start with `target: ldm.data.personalized.PersonalizedBase`) can take any parameter that the PersonalizedBase class takes. So you can just add `flip_p: 0.0` to both the train and validation parameter blocks to disable flipping.

The result should look like this:
```data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    wrap: false
    train:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512
        set: train
        per_image_tokens: false
        repeats: 100
        flip_p: 0.0
    validation:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512
        set: val
        per_image_tokens: false
        repeats: 10
        flip_p: 0.0
```

**Comment by LexCybermac** [comment]
Oh this is brilliant! I've gone ahead and made the change to my config file and am now happily training away. Thanks so much for the speedy reply too :D

**Comment by LexCybermac** [comment]
Not to channel Columbo too much with the "ahh just one more thing" after closing a thread but the question did just occur to me to ask if are there any other augmentation options which can be explicitly set from the config file?

I understand that generally speaking data aug exists for a very good reason, but I do find myself curious about experimenting with any other options there might be.

**Comment by rinongal** [comment]
The code isn't using any other augmentations, no. You can disable things like center cropping if you're so inclined.

If you want to add more data augmentations yourself, you can of course try that, but I'd focus on things which you wouldn't mind seeing as part of the output images (so maybe cropping parts of the image is fine, but changing the colors is not).

**Comment by rinongal** [comment]
The code isn't using any other augmentations, no. You can disable things like center cropping if you're so inclined.

If you want to add more data augmentations yourself, you can of course try that, but I'd focus on things which you wouldn't mind seeing as part of the output images (so maybe cropping parts of the image is fine, but changing the colors is not).

**Comment by LexCybermac** [comment]
I'd be very interested in disabling centre cropping, how might I go about specifying that in the config?

**Comment by rinongal** [comment]
Haa, its off by default. You can re-enable it by adding a center_crop: true to the params in the same spot as above

**Comment by LexCybermac** [comment]
Oh phew lmao, was hoping that was the case :D Thanks for getting back to put my concern I might be training with sub-optimal parameters to rest.
