### ISSUE TITLE
Question about the parameterization "eps" and "x0"

### ISSUE THREAD

**Issue by lizc126** [rinongal/textual_inversion#135]
Hi,

Thank you for brilliant work and code repo. I have a question regarding the parameterization. I see the default is set to "eps", where the UNet model predicts noise and calculate loss wrt the original randomly generated noise. And if it is changed to "x0", UNet model will predict the image (in latent space) and calculate loss wrt the ground truth image (in latent space). Am I understanding this correctly? But if I set it to "x0", the sample generated seemed to be very off.  Hope you can give me some ideas.

Thank you!

**Comment by rinongal** [comment]
Hi,

Sorry for the extremely late reply. The configuration you're referencing to is part of the original LDM code, and if you want to change it you need to actually re-train a model that uses the new parametrization. 

Basically, what you're trying to do now is take a network that was trained to predict noise and treat its output as if it was the x0 prediction itself. This of course creates issues.

**Comment by lizc126** [comment]
> Hi,
> 
> Sorry for the extremely late reply. The configuration you're referencing to is part of the original LDM code, and if you want to change it you need to actually re-train a model that uses the new parametrization.
> 
> Basically, what you're trying to do now is take a network that was trained to predict noise and treat its output as if it was the x0 prediction itself. This of course creates issues.

Thank you for your reply!
