### ISSUE TITLE
Some questions about extra applications (merge_embeddings, templates and OOD)

### ISSUE THREAD

**Issue by Robin-WZQ** [rinongal/textual_inversion#138]
Hello. Thank you for your great work. I was trying to use your code and got great results, thank you very much again!

Q1: Is there any possible to merge three models or even more models? Cause I want to merge three or more styles in one picture. Do you have done any related test?

Q2: Besides, there is an another dimension of my data (e.g. composition of the painting), I want to use templates like 'a painting in the composition of {}'. Do you think textual_inversion can handle it?

Q3: I find that my data is a liitle bit OOD to the model you provide, and I want to fine-tuning 'txt2img-f8-large.ckpt' with 'image-caption' pairs first, then train a textual_inversion model. I replaced your model with sd-v1-4-full-ema.ckpt to see if they are compatiable but got this error:

`
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
TypeError: __init__() missing 1 required positional argument: 'personalization_config'
`

It seems like you added some parameters in the original model.  I want to the same modification, how can i make it?

Thanks a lot!

Robin

**Comment by rinongal** [comment]
Hi,

Q1: We did not try it, but the merging script should in principle be able to merge more than 2 concepts (worst case you can run the script twice: first merge 2 and then merge the result with the final one).

Q2: I haven't experimented with this level of granularity. In principle we've seen that inversion can capture details like poses, viewpoints and styles, so there's a good chance it can capture the composition as well. I can't really guarantee anything there.

Q3: If you want to train with stable diffusion, you need to use the stable diffusion config in `configs/stable-diffusion/v1-finetune.yaml` or `configs/stable-diffusion/v1-finetune_unfrozen.yaml`

**Comment by Robin-WZQ** [comment]
Got it, thank you for your replying!
