### ISSUE TITLE
max_vectors_per_token 

### ISSUE THREAD

**Issue by fido20160817** [rinongal/textual_inversion#139]
what does 'max_vectors_per_token ' means? under what kind of situation? any example?

**Comment by rinongal** [comment]
It was used as part of the experiment in the paper where we progressively add more vectors to the inversion. Probably not relevant to you unless you set progressive_words to True in the config.

**Comment by fido20160817** [comment]
Thanks for your response. Another stupid question, what does 'progressive_words' means?

**Comment by rinongal** [comment]
We describe this experiment in the paper. It is equivalent to starting training with only a single word representing your concept and adding more and more words as training progresses

**Comment by fido20160817** [comment]
many thanks!
