### ISSUE TITLE
Unique placeholder string

### ISSUE THREAD

**Issue by hlky** [rinongal/textual_inversion#14]
Can placeholder string be something unique like `0xCAFEBABE` for training then used like `a photo of 0xCAFEBABE` for inference?

**Comment by rinongal** [comment]
The string has to be something which the model's tokenizer matches to a single token. I don't think this string will work. If you don't want to use things like "*" or "@" you can often use characters in other alphabets ("א", "ב") and some emojis.

**Comment by hlky** [comment]
I see, any way to change this? 

> you can often use characters in other alphabets
Often or always? any known limitations?

I assume merging embeddings with  "*" and embeddings with "@" would allow either to be used in the prompt, I would be interested to know if 2 or more embeddings can be used together in the same prompt.

More than a single token would just allow more user-friendly prompt words

**Comment by rinongal** [comment]
It depends on the specific model and the tokenizer used, so the best tip I can give here is 'try some and see if they give you an error'. It's part of the reason for the assertion in embedding_manager.py that I see people keep commenting out :)

The embedding merging code actually lets you swap the placeholders in case there's a conflict, so if you're worried about that -  there's no need to be. You can train everything with e.g. * and then just swap them out later when merging.

In the LDM version you can use 2 embeddings in the same prompt, see the paper or the project page for examples of what it looks like. I haven't tested it with the SD code yet.

The problem with using more than a single token is that it complicates the implementation significantly. 
If you want to make it more user-friendly, you can just add some replacement code that changes the prompt before it is fed into the model. For example, you could add code which replaces the string "mypersonalword" with "*" and then continues as normal, in which case you'd be able to just use "mypersonalword" when prompting.

**Comment by TabuaTambalam** [comment]
Shouldn't placeholder string (actually, a special one token char) be dynamically assigned?
Here's my approch: https://github.com/TabuaTambalam/DalleWebms/blob/main/docs/debugging/LDM_SR_jited.ipynb
In `class BERTEmbedder` ,you can insert that 1x768, f32 array (`xxx1.bin`) to where string `<xxx1>` is.

(My SD's text transformer is JITed so using my own embedding_manager implement)

Also can anyone or @rinongal share your `embeddings_gs-9999.pt` (that 6kb one) here?
I want to test multiple-insert but don't want to spend another 8 hours to fit/train one.

Also the script to turn the .pt into a 1x768, f32 array:
```
import torch
epo=torch.load( '/content/embeddings_gs-4500.pt' ,map_location=torch.device('cpu'))
epo['string_to_param']['*'][0].detach().numpy().tofile('majipuri.bin')
```

**Comment by rinongal** [comment]
For me, having the same placeholder meant that I don't have to play some long term memory game with my pre-trained embeddings. I always know what string to use when prompting for the concept. If someone wants more specific control, it's available in the config (and for the multi-concept cases, the merging code lets you re-select placeholders to avoid conflicts). I'm not sure if there's added benefit assigning random placeholders. 

For the embeddings_gs request, here's one for LDM, hopefully that's what you need: [cat_5k.zip](https://github.com/rinongal/textual_inversion/files/9430363/cat_5k.zip)

**Comment by rinongal** [comment]
Closing since I think this is more or less resolved. If you have further questions, feel free to re-open.
