### ISSUE TITLE
question about 'def next_step(...)'

### ISSUE THREAD

**Issue by fido20160817** [rinongal/textual_inversion#140]
'timestep, next_timestep =  min(timestep - self.scheduler.config.num_train_timesteps // self.scheduler.num_inference_steps, 999), timestep'
should be:
'timestep, next_timestep =  timestep, min(timestep + self.scheduler.config.num_train_timesteps // self.scheduler.num_inference_steps, 999)'
am I right?
I have tested both and the results are all normal. But I think the latter coding is right.

**Comment by rinongal** [comment]
This part is not our code. If you have questions about the original LDM code you should hop on to [their own repository](https://github.com/CompVis/latent-diffusion)

**Comment by fido20160817** [comment]
Thanks. It's my mistake. I mix your code with others.
