### ISSUE TITLE
optimization on null text

### ISSUE THREAD

**Issue by fido20160817** [rinongal/textual_inversion#141]
Hi, the null text is optimized over the different timesteps. I am wondering whether it is an alternative solution to optimize unet itself over different timesteps only for this kind of condition? (copy unet and frozen it ahead, then for normal text input, use the frozen ones; for null text, use the optimized unet).

**Comment by rinongal** [comment]
We don't actually modify the u-net or the null text in any experiment that uses the frozen config. 

You can look at [Null text inversion](https://arxiv.org/abs/2211.09794) for ideas on what you can do by tuning the null text. I'm sure there are also more ways to use it.

**Comment by fido20160817** [comment]
oh, sorry, I mix your codes and Null text inversion. Thanks!
