### ISSUE TITLE
Training for model based on SD1.5 got bad result

### ISSUE THREAD

**Issue by steelywing** [rinongal/textual_inversion#142]
I have tried training on several SD1.5 base model (Ex: ChillOutMix, NED, ...) for person, but all get bad result.
If I use the same dataset to train on SD1.5, the result is good, even use the textual inversion on other SD1.5 base model the gen image also good.

I am using SD WebUI to train.

Image train on SD 1.5, then generate ChillOutMix:
![image](https://user-images.githubusercontent.com/2720049/224644803-5b846f68-9a59-4603-993b-7328e30a4b74.png)

Image train on ChillOutMix, then generate ChillOutMix:
![image](https://user-images.githubusercontent.com/2720049/224643408-a466cebf-f38f-4585-9dc0-86ab9816f4c4.png)

1 of training dataset:
![image](https://user-images.githubusercontent.com/2720049/224643965-15b9bc90-0eaf-416b-bdbe-783e53342770.png)

**Comment by rinongal** [comment]
Are the finetuned models you are training on also realistic models? Or are they more restricted (e.g. to artistic styles)?

**Comment by steelywing** [comment]
> Are the finetuned models you are training on also realistic models? Or are they more restricted (e.g. to artistic styles)?

The model I training on is also photo realistic model, but A model itself will produce a face with A character, B model will produce B face, as far as I understand (they should have finetuned the face), textual inversion should get the face weights better on their own model, isn't it?

I can train on SD1.5 with no issue, I just want to understand why it get worse result, I am thinking if I am not setting config properly, thanks for your reply~

(I edit the first post for clearer descript the train and generate model that I use)

**Comment by steelywing** [comment]
I found if I change the vectors to >= 16, the result a lot better, I see some YouTube guide says vector 2~4 for character training is enough, may be he only trained on SD basic model, thanks you
