### ISSUE TITLE
RAM needs - SOLVED

### ISSUE THREAD

**Issue by kaosbeat** [rinongal/textual_inversion#15]
Hi,

running

```
python main.py  --base configs/latent-diffusion/txt2img-1p4B-finetune.yaml 
                          -t 
                          --actual_resume models/ldm/text2img-large/model.ckpt 
                          -n oldphone 
                          --gpus 0  
                          --data_root inputimg/ 
                          --init_word oldphonesynth

Global seed set to 23
Running on GPUs 0
Loading model from models/ldm/text2img-large/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 872.30 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
```
It suddenly halts after a minute or so saying "Killed"
```
Killed
```
Apparently I had to free up loads of RAM to get the training started, 32Gb was barely enough, I had to kill all open applications. Just posting here so you know what to do when you encounter "Killed"

**Comment by rinongal** [comment]
Just a heads up:

1) You can reduce the batch size in the config file if you're running OOM, though it shouldn't be reaching 32 GB with the LDM version and the default batch size to begin with. 
I'm not sure if there's any changes in the windows version which bloat up the requirements...

2) The init_word is not the placeholder string used for generation. It's meant to be a single token word that provides the initial point from which we optimize the new word. You probably want to use 'phone' and not 'oldphonesynth'.

**Comment by kaosbeat** [comment]
yeah the memory peaked at the start.. seems to be lower further down the training. I'm on ubuntu 22.04 RTX5000 16Gb + 32Gb ram
I had good results using "phone" (it wouldn't accept oldphonesynth, like explained in the manual)
trying stable diffusion now. now the VRAM is an issue
`
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 15.75 GiB total capacity; 13.04 GiB already allocated; 721.06 MiB free; 13.82 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

 `
any chance for a quick tweak here , only missing about 300Mb of VRAM

**Comment by kaosbeat** [comment]
I changed 
  ```
  unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
            num_heads: 4

```
from `num_heads: 8`

now using about 12Gb of VRAM, I have no Idea what the impact on training will be

**Comment by rinongal** [comment]
I'd play with things like batch size before I change the number of attention heads. This sort of change might cause the model to 'forget' existing concepts or fail to parse some texts.

**Comment by kaosbeat** [comment]
Yes, you are right.
I clearly forgot somethings, interesting output nonetheless :)
Changing the batch size to 1 makes it run om my 16Gb RTX5000 and output is what could be expected
