### ISSUE TITLE
error when trying to merge embeddings

### ISSUE THREAD

**Issue by agcagc** [rinongal/textual_inversion#16]
When I try to merge 2 embeddings I get this error (on ubuntu wsl on windows 11):

Traceback (most recent call last):
  File "merge_embeddings.py", line 56, in <module>
    manager = EmbeddingManager()
  File "/home/user/textual_inversion/ldm/modules/embedding_manager.py", line 59, in __init__
    get_embedding_for_tkn = partial(get_embedding_for_clip_token, embedder.transformer.text_model.embeddings)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BERTTokenizer' object has no attribute 'transformer'

**Comment by rinongal** [comment]
Are you working with the stable diffusion code or with the LDM code? The embedding merger has not been updated for the (still unofficial!) Stable Diffusion code. I'll probably get to it over the weekend.

**Comment by agcagc** [comment]
Ok thanks, I was using stable diffusion, other than that it works very well

**Comment by NathanielAyer** [comment]
I got this same error running merge_embeddings.py trying to merge two pt files produced by Textual Inversion, running on Amazon Linux 2. Same error in Windows 11.

**Comment by 1blackbar** [comment]
For now wit this coed you can use multiple embeddings without merge : https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by rinongal** [comment]
This should now be working. To merge SD checkpoints just add the `-sd` flag to the merge command. Feel free to re-open if you have more issues.
