### ISSUE TITLE
Textual Inversion and Stable Diffusion create identical images with same prompt and seed, even with --embedding_path to my pt file

### ISSUE THREAD

**Issue by NathanielAyer** [rinongal/textual_inversion#17]
I created some new pt files today and then tried making new images with them. If I run these commands...
`python scripts/stable_txt2img.py ... --embedding_path new.pt` in Textual Inversion
and
`python scripts/txt2img.py` in Stable Diffusion
with the same seed and prompt, I get the same images.

**Comment by XodrocSO** [comment]
What string did you use? default?  

did you check the images in the logs folder to see if it looked like they were making progress?

**Comment by NathanielAyer** [comment]
> What string did you use? default?
While training TI? No. I set a custom init_word for each run.
For the prompt? "x in the style of y" mostly, where one or the other is the concept I trained on. Also "a photo of x."

Someone on the SD Discord recommended that I try literally using "*" and not the word I inputted while training TI. I'm going to try that and see what happens.

> did you check the images in the logs folder to see if it looked like they were making progress?
Yes. The images in the logs folder looked really good. Those definitely looked like TI was learning the concepts. But when I try creating new images in TI based on the resulting pt files, the images look exactly the same as running SD without the pt files.

**Comment by aperullo** [comment]
So the init word

**Comment by NathanielAyer** [comment]
> So the init word is just where the model begins in the vector space if I understand the paper correctly. * Is the actual "word" the model knows represents your concept. Once training is done you no longer use the init word. You use the placeholder

Thanks! I'm running stable_txt2img with "*" instead of my init_word and it's working as expected now. Do you know how this is going to work when eventually we're able to merge pt files? Like in the "Composition" section of the page https://textual-inversion.github.io/ how would they reference two different concepts?

**Comment by rinongal** [comment]
@aperullo is correct. Init_word is just the beginning of the optimization. "*" is the placeholder unless you change it in the config.

@NathanielAyer The checkpoint merging script lets you re-select the placeholder if there's a conflict between the checkpoints. We typically used "@" as the second placeholder, so our compositions were done with "* in the style of @"

**Comment by NathanielAyer** [comment]
Thanks for the info! I think I should close this issue. This is probably a case of RTFM for me. But if you have time, maybe some more explicit instructions on the web page instead of in the paper would be helpful.
