### ISSUE TITLE
Resuming from log checkpoint

### ISSUE THREAD

**Issue by vasimr** [rinongal/textual_inversion#22]
Is resuming from a log checkpoint supported?

I did try using the `--actual_resume` and `--embedding_manager_ckpt` arguments in a few combinations, but they all lead to crashes. So I must be missing something. If this is supported, what should the argument structure be?

**Comment by rinongal** [comment]
Not currently supported but it was requested here as well: https://github.com/rinongal/textual_inversion/issues/4
I'll add it over the weekend.

**Comment by rinongal** [comment]
Done. You can now continue from an existing embedding checkpoint by using `--embedding_manager_ckpt <path_to_ckpt>`.
