### ISSUE TITLE
datesets

### ISSUE THREAD

**Issue by myyy777** [rinongal/textual_inversion#23]
Could you please provide some datasets of your demo? 
my email：mayuan9988@gmail.com

**Comment by rinongal** [comment]
You can find most of them [here](https://drive.google.com/drive/folders/1d2UXkX0GWM-4qUwThjNhFIPP7S6WUbQJ?usp=sharing).

I'll add others as I get the permissions to upload them. If there's a particular one missing that you'd like, let me know.
