### ISSUE TITLE
face issue on img2img with text inversion

### ISSUE THREAD

**Issue by putuoka** [rinongal/textual_inversion#24]
not only the style has changed but also the face has become dissimilar

**Comment by 1blackbar** [comment]
I found this in the paper----

Text-to-image models can be used to generate misleading content and promote disinformation. Personalized
creation could allow a user to forge more convincing images of non-public individuals. However, our model
does not currently preserve identity to the extent where this is a concern.

**Comment by woctezuma** [comment]
> i hope im wrong

The text is pretty clear.

> "our model does not currently preserve identity"

**Comment by rinongal** [comment]
You *might* be able to get something done with SD. Our paper was written when LDM was all we had available, and LDM itself is pretty terrible for faces. I can't make any guarantees on SD though.

**Comment by rinongal** [comment]
Either way, this seems to be about something we warned would be unlikely to work, and it's trying to combine it with another method at that, so I'm closing the issue for now. I might look into img2img + textual inversion in the future, but its very likely the community will figure it out first.
