### ISSUE TITLE
Interval to save embeddings during training

### ISSUE THREAD

**Issue by dogarrowtype** [rinongal/textual_inversion#28]
Hi, I've trained a few textual inversions with stable diffusion with mixed success, and I'm wondering if it's possible to change how often embeddings are saved during training.
I've looked through the configs/stable-diffusion/v1-finetune.yaml, but I can't find the option to change how often embeddings are saved to disk, or if it's even possible to adjust this.
Having more granular checkpoints to pick from after the training is done would be very helpful to get more useful results. Currently, my custom v1-finetune.yaml is saving every 600 steps, but it would be great to have it save on every epoch.
Is this possible, and what would I need to change to make this happen?

**Comment by rinongal** [comment]
I'll add it to the config, should be a small change.

**Comment by nicolai256** [comment]
> I'll add it to the config, should be a small change.


https://github.com/nicolai256/Stable-textual-inversion_win/commit/5bfe466a4ac7e02290f2998db32f56b70e654ca7
https://github.com/nicolai256/Stable-textual-inversion_win/commit/db59eb85d13d3466a21a1ddd4aff2b8d0d4fd5dc

**Comment by rinongal** [comment]
Done
