### ISSUE TITLE
About the role of PLMS

### ISSUE THREAD

**Issue by CS123n** [rinongal/textual_inversion#31]
Hi, congratulations on your wonderful job!
https://github.com/rinongal/textual_inversion/blob/83a19a4784236e5bd7eaa2b68a98942a21dafc0f/ldm/models/diffusion/plms.py#L11
I find that you also provide the sampling method PLMS from [Pseudo Numerical Methods for Diffusion Models on Manifolds](https://arxiv.org/abs/2202.09778). Is it useful in your situation? If it is true, it would be nice to add a note about it in the readme.
Thanks!

**Comment by rinongal** [comment]
Hi, and thanks!

The PLMS code is actually part of the LDM code. We did not implement / test it ourselves. I'll check if it works with our modifications and update the readme accordingly if it does.
