### ISSUE TITLE
What is the newly added config v1-finetune_unfrozen.yaml for?

### ISSUE THREAD

**Issue by XavierXiao** [rinongal/textual_inversion#33]
Does this potentially support fine-tuning the diffusion model, as in the dreambooth paper?

**Comment by rinongal** [comment]
It's for the pivotal tuning method from our own appendix which helps a bit with the editability issues we're having with Stable Diffusion. Unfortunately it's also not stable enough ATM so still a WIP.

I don't plan on implementing the DreamBooth stuff myself, but if anyone wants to pick it up and make a PR, it shouldn't be too much work.
