### ISSUE TITLE
Lightning Error

### ISSUE THREAD

**Issue by nephi-dev** [rinongal/textual_inversion#36]
Strange error when training on SD: `pytorch_lightning.utilities.exceptions.MisconfigurationException: No 'test_dataloader()' method defined to run 'Trainer.test'`.

After some steps(6000 if i'm not wrong) I got this.

**Comment by rinongal** [comment]
That's training reaching the end and running a nom-existent test routine. I'll update the code to print a proper message. If you want to train for longer, just adjust the maximal number of steps in the config file (max_steps all the way at the bottom).

**Comment by nephi-dev** [comment]
thanks, i'll do that
