### ISSUE TITLE
Support for Image Prompts

### ISSUE THREAD

**Issue by dboshardy** [rinongal/textual_inversion#37]
Do any of the current revisions of models support image+text prompt to guide the sampling?

I'm looking through the code and see support for masks, which makes me think I should be able to pass an image in w/o a mask.  

Is there more to do to enable this?

**Comment by WhiteSigility** [comment]
I can confirm that my finetuned checkpoint works fine with Stable Diffusion's img2img technology per the web UI:

- https://rentry.org/GUItard
- https://github.com/hlky/sd-enable-textual-inversion

In fact, I would say it's a lot more useful in an img2img context - my text prompts tend to produce a lot of "samey" or incoherent results after finetuning. But with image guidance I get a ton of variety.
