### ISSUE TITLE
Question about resuming from checkpoint

### ISSUE THREAD

**Issue by inflamously** [rinongal/textual_inversion#38]
Hey there,

so I have this one colab of mine with a command of:

`
command = "python main.py" +\
            " --base " + model_config +\
            " --actual_resume " + model_checkpoint +\
            " -t " +\
            " -n " + name +\
            " --gpus 0, "+\
            " --data_root " + train_images +\
            " -l logs " +\
            " --embedding_manager_ckpt " + train_checkpoint_file
`

where I load up a present model, checkpoint file and try to resume from that point of time.

train_checkpoint_file = _logs/<custom_logs>/checkpoints/embeddings_gs-2499.pt_
model_checkpoint = _ldm/stable-diffusion/model.ckpt_

Now my question is: Is it normal for when trying to resume from checkpoint that the epoch starts at 0 with 0 steps?
How do I know if previous run was being continued on.
Is there an example command that can be used?

Thanks in advance and for this awesome project. :)

**Comment by rinongal** [comment]
Your command looks fine.
It's normal that the counters start again from 0, yes. Our checkpoint doesn't store any information about the training step.

Easiest way to verify that the checkpoint is loaded correctly is to just look at the output images during training. 
(If it didn't load correctly, your images should look like they did at the start of training).

**Comment by inflamously** [comment]
Ah thanks a lot :)
