### ISSUE TITLE
Higher vector number

### ISSUE THREAD

**Issue by nephi-dev** [rinongal/textual_inversion#39]
is worth using a higher value for the config `num_vectors_per_token`, like 2048 or even higher?

**Comment by rinongal** [comment]
No. The encoder has a fixed input length (77 for SD), so there's no point going above this number. Even then, I wouldn't try anything close to that because you need room for the rest of the prompt.

**Comment by nephi-dev** [comment]
@rinongal, so, 8 will be ok?

**Comment by rinongal** [comment]
8 is fine, yes. You may end out overfitting the image, but it's reasonable enough to try.
