### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'embedding_reg_weight'

### ISSUE THREAD

**Issue by thibaudart** [rinongal/textual_inversion#40]
I train with this command with success: 

 python main.py --base configs/stable-diffusion/v1-finetune.yaml                -t                --actual_resume ../stable-diffusion-main/models/ldm/stable.ckpt               -n test1                --gpus 0,                --data_root img/loran               --init_word l 

but when I launch this command

python scripts/txt2img.py --ddim_eta 0.0                           --n_samples 1                           --n_iter 2                           --scale 10.0                           --ddim_steps 50                           --embedding_path logs/loran2022-08-29T16-27-54_test1/checkpoints/embeddings_gs-6099.pt                           --ckpt_path  ../stable-diffusion-main/models/ldm/stable.ckpt                           --prompt "a photo of *"

I got this error:

Loading model from /home/.../stable-diffusion-main/models/ldm/stable.ckpt
Traceback (most recent call last):
  File "/home/.../textual_inversion/scripts/txt2img.py", line 120, in <module>
    model = load_model_from_config(config, opt.ckpt_path)  # TODO: check path
  File "/home/.../textual_inversion/scripts/txt2img.py", line 18, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/home/.../stable-diffusion-main/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/.../stable-diffusion-main/ldm/models/diffusion/ddpm.py", line 510, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'embedding_reg_weight'

**Comment by rinongal** [comment]
If you're using the stable diffusion model, you should work with scripts/stable_txt2img.py and not scripts/txt2img.py

You should also make sure its using the right config (configs/stable-diffusion/v1-inference.yaml) but if you use stable_txt2img.py then this will be the default.

**Comment by rinongal** [comment]
Can you have a look at https://github.com/rinongal/textual_inversion/issues/21#issuecomment-1228143520 ? I think you have the same issue. Your stack trace seems to be pointing at a stable-diffusion-main which is another version of the SD repo :)

Also - if you set the --config, make sure you're using v1-inference.yaml and not v1-finetune.yaml.

**Comment by thibaudart** [comment]
I confirm, same issue as #21 
thanks a lot
