### ISSUE TITLE
Dtype mismatch when using embeddings with SD

### ISSUE THREAD

**Issue by ClassicDirt** [rinongal/textual_inversion#43]
I've trained my model using the v1-finetune Stable Diffusion config. Everything went smoothly until I actually tried to use the model with Stable Diffusion txt2img. When I run txt2img with my embeddings loaded, I get this error:
```Index put requires the source and destination dtypes match, got Half for the destination and Float for the source.```

**Comment by SeverianVoid** [comment]
I am having this same issue, did you manage to fix this if so how?
