### ISSUE TITLE
error during training setup: 'int' object has no attribute 'strip'

### ISSUE THREAD

**Issue by nylki** [rinongal/textual_inversion#45]
Hi there,
first of all: thank you for work and this repo!

I was trying to run a training session using the SD model as follows:

```
(ldm_2) ➜  textual_inversion git:(main) ✗ which python
~/.conda/envs/ldm_2/bin/python

python main.py --base configs/stable-diffusion/v1-finetune.yaml -t --actual_resume ../sd-v1-4.ckpt -n sheep --gpus=1 --data_root /home/tom/Projects/StableDiffusion/training_images/sheep --init_word "toy"
```

I did create a new environment with conda and activated it. I have however renamed `ldm` to ` ldm_2` in ` environment.yaml`, (shouldn't affect anything right?)

So far so good, but after some seconds I get the following:

> Traceback (most recent call last):
  File "main.py", line 762, in <module>
    ngpu = len(lightning_config.trainer.gpus.strip(",").split(','))
AttributeError: 'int' object has no attribute 'strip'

Full log output is attached. Any ideas what this could be? 

[errorlog.txt](https://github.com/rinongal/textual_inversion/files/9478800/errorlog.txt)

**Comment by rinongal** [comment]
Replace `--gpus=1` with `--gpus=0,` (including the trailing comma). This argument to --gpus is a list of the gpu indices you want to use, not the number of gpus.

**Comment by nylki** [comment]
@rinongal thank you! I tried setting it to `0`  before, but it was indeed the trailing comma.
