### ISSUE TITLE
How to achieve "Bipartite Inversion" ?

### ISSUE THREAD

**Issue by kingofprank** [rinongal/textual_inversion#52]
Thanks for amazing work! I got a problem when I want to achieve the "Bipartite Inversion" in this paper. In my opinion, the sampling process can be viewed as z_0 = DM(c, z_t), we can obtain x_t -> x_{t-1} in each step. However, in the inversion process, we fixed z_0 and c, reverse the Eq 12 in the DDIM to achieve x_{t} -> x_{t+1}. There are no random factors in this process, everything is deterministic.

I use this [link](https://github.com/phizaz/diffae/blob/959aa82b48f319be01899eb5ee48e284f28cb854/diffusion/base.py#L670) as a reference. But after 250 steps of diffusion and denoising, a picture full of noise was obtained ( unconditional guidance scale is set as 0). Could you provide some information or correct codes about the "Bipartite Inversion" process? Thanks!

**Comment by rinongal** [comment]
My code for the bipartite inversion is a bit messy, but if you want to give me an e-mail address I'll send it to you.
Alternatively, have a look at the equations in Appendix F of [this paper](https://arxiv.org/abs/2105.05233).

**Comment by kingofprank** [comment]
> My code for the bipartite inversion is a bit messy, but if you want to give me an e-mail address I'll send it to you. Alternatively, have a look at the equations in Appendix F of [this paper](https://arxiv.org/abs/2105.05233).

Thank you very much! My email address is "kingofprank1024@gmail.com".

**Comment by rinongal** [comment]
Sent

**Comment by kingofprank** [comment]
Thanks for your help~
