### ISSUE TITLE
Help with set up please

### ISSUE THREAD

**Issue by Aditya-Bahl** [rinongal/textual_inversion#55]
Hi, 

Hope you are doing well. I am new to this and needed some help with the setup, I  cloned the repo in visual studio and ran the "conda env create -f environment.yaml"

However, I am getting a "ResolvePackageNotFound: 
  - cudatoolkit=11.3" 

error. 

Would appreciate help on what, I should do?

**Comment by Aditya-Bahl** [comment]
Figured it out, solution below: 

"I had same problem and found your question googling for it. ResolvePackageNotFound error describes all packages not installed yet, but required. To solve the problem, move them under pip section."

**Comment by rinongal** [comment]
As this seems to be resolved, I'm going to mark this as closed. Feel free to reopen if you still have an issue.
