### ISSUE TITLE
How to generate "a image1[inverse token1] with the style from image2[inverse token2]" with this pretrained model?

### ISSUE THREAD

**Issue by BEaN001** [rinongal/textual_inversion#57]

**Comment by rinongal** [comment]
If you have two checkpoints trained on two different concepts, you can merge them into a single checkpoint with `merge_embeddings.py`. See the readme for a run command example. If both the models are using the same placeholder (e.g. "*"), this will prompt you to change the placeholder for one of them (e.g. to "@"). 

Once you do this, you can just use the two individual tokens in the same prompt. For example: "An image of * in the style of @".
