### ISSUE TITLE
Are the 'imagenet_templates_small' templates in personalized.py used just for visual inspection, or actual testing?

### ISSUE THREAD

**Issue by CodeExplode** [rinongal/textual_inversion#59]
I've seen some discussion about getting better outcomes by changing the imagenet_templates_small entries in personalized.py to better match the subject (e.g. change to 'a drawing of {}' if building an embedding for an animated character, or 'a man wearing {}' if it's a hat which you want to be shown on people's heads), or even just replacing them with a single '{}' to test whether the object itself is recreated, but I'm unsure if this is in reference to visual inspections during training, or if those phrases are used to generate test cases which are evaluated internally as part of the process.

**Comment by rinongal** [comment]
These phrases are also used during the training. Basically, the model trains to reproduce the training set images when it sees random sentences from those templates and the {} replaced by the placeholder string.

Replacing the templates with a single '{}' is giving me consistently worse results, to the point of failing to create basic reconstructions of the object. However, I haven't tried mixing it with things like dramatic increases in the number of vectors assigned to the token.

**Comment by CodeExplode** [comment]
Thanks. I've changed the prompts three times now and wasn't 100% sure if they were working, but yeah a blank {} didn't seem to work for me (but then I'm not doing a single object in isolation where it might). Glad to know those do play a factor.
