### ISSUE TITLE
Some output images are blurry while others are sharp

### ISSUE THREAD

**Issue by dboshardy** [rinongal/textual_inversion#60]
Using Stable Diffusion, some times, within the same batch, some of the images are very sharp, but others are blurred.  I've tried changing the steps higher, but still getting similar results where some are blurry and others not.

**Comment by rinongal** [comment]
Are some of your training set images blurry?

**Comment by dboshardy** [comment]
I'm not sure if it's related, but I'm also getting very odd patterns showing up in the background and in other surfaces instead of nice flat colors that match the source images.

The source images have blank, solid color background, but i'm getting stuff like this when applying the embedding.  Is this overfitting?  I'm using the stable diffusion patch so it might be that too.

<img width="129" alt="Screen Shot 2022-09-08 at 9 52 05 AM" src="https://user-images.githubusercontent.com/2131537/189159569-c0fc8b94-c32b-4beb-8741-406cf435b8a6.png">

**Comment by dboshardy** [comment]
Upping the output image size to 512x512 fixed this.
