### ISSUE TITLE
Suddenly process outputs bad images

### ISSUE THREAD

**Issue by dboshardy** [rinongal/textual_inversion#63]
Overnight, the codebase is now outputting almost entirely grey images with some weird artifacts.  This is with embeddings that previously produced great results.  

Looking at some dependencies, huggingface/transformers changed this morning.  I tried deleting the cache and loading the frozen clip embeddings from the revision before the change but that also does not work.  

What else might have changed externally that this suddenly isn't working for training or inference?

This is using stable diffusion FWIW.

**Comment by dboshardy** [comment]
I've tried deleting and recreating the conda env as well to no effect.

**Comment by dboshardy** [comment]
A fresh install seemed to fix this. I have no idea what went wrong.  I think I narrowed the issue down to when the sampler is decoding.  In the stdout log text, it runs DDIM Sampler: up to 100%, then in the version that _doesn't_ work, it writes out 
```
Sampling:   0%|                                                                                                                                                                                          | 0/1 [00:00<?, ?it/s]```

but in the version that does work, I get:
```
Sampling: 100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [01:24<00:00, 84.48s/it]
```

**Comment by rinongal** [comment]
They may have had an issue with the release which was later patched? 
I saw some issues on the diffusers version of inversion that were later fixed by an update.

Either way, if this is working for you now - then I won't delve into it. Unless others have the same problem?

**Comment by dboshardy** [comment]
@rinongal I figured out it was using a broken version that had changed at some point.  I didn't see the `-e .` in the `environment.yaml` and did not reinstall.
