### ISSUE TITLE
How to use huggingface concepts Or is there a guide doc of original IMG->pt->SD？

### ISSUE THREAD

**Issue by inspire-boy** [rinongal/textual_inversion#64]
All your work is amazing!

I feel the guide in this rep is Incoherence. especially those "path/to" is Confusing.

If a female colleague asks to use her photo to generate a style for her after watching the pictures output by SD.What should I do?

So,If someone has a esay doc-guide with an example in ubuntu18/nvidiaA5000-24G?

Thanks!

**Comment by rinongal** [comment]
If you want to use the huggingface concepts, you'll have to follow their colab / guide. This repo has no support for the huggingface concepts.

If you do use this repo, just put your images in a folder, for example: /home/inspire-boy/my_images/
And then point do them when you run the script by using `--data_root /home/inspire-boy/my_images/`

**Comment by inspire-boy** [comment]
> 如果你想使用拥抱脸的概念，你必须遵循他们的 colab / guide。这个 repo 不支持拥抱脸的概念。
> 
> 如果您确实使用此 repo，只需将您的图像放在一个文件夹中，例如：/home/inspire-boy/my_images/ 然后在运行脚本时使用`--data_root /home/inspire-boy/my_images/`

Thanks a lot! I will try it immediately.

**Comment by inspire-boy** [comment]
> 如果你想使用拥抱脸的概念，你必须遵循他们的 colab / guide。这个 repo 不支持拥抱脸的概念。
> 
> 如果您确实使用此 repo，只需将您的图像放在一个文件夹中，例如：/home/inspire-boy/my_images/ 然后在运行脚本时使用`--data_root /home/inspire-boy/my_images/`

Do you now this why this error appears?

python main.py --base configs/stable-diffusion/v1-finetune.yaml -t --actual_resume "models/ldm/text2img-large/model.ckpt" -n "liangbox" --data_root ../liangbox --init_word "box" --placeholder_tokens "liangbox"

output:

Global seed set to 23
Loading model from models/ldm/text2img-large/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 64, 64) = 16384 dimensions.
making attention of type 'vanilla' with 512 in_channels
Some weights of the model checkpoint at openai/clip-vit-large-patch14 were not used when initializing CLIPTextModel: ['vision_model.encoder.layers.23.self_attn.out_proj.bias', 'vision_model.encoder.layers.0.self_attn.out_proj.weight', 'vision_model.encoder.layers.5.mlp.fc2.weight', 'visual_projection.weight', 'vision_model.encoder.layers.1.mlp.fc1.bias', 'vision_model.encoder.layers.9.mlp.fc1.bias', 'vision_model.encoder.layers.4.self_attn.k_proj.bias', 'vision_model.encoder.layers.17.self_attn.v_proj.bias',......................
...............
............
- This IS expected if you are initializing CLIPTextModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing CLIPTextModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "main.py", line 614, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "main.py", line 29, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/root/textual_inversion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "/root/textual_inversion/ldm/models/diffusion/ddpm.py", line 481, in __init__
    self.init_from_ckpt(ckpt_path, ignore_keys)
  File "/root/textual_inversion/ldm/models/diffusion/ddpm.py", line 205, in init_from_ckpt
    missing, unexpected = self.load_state_dict(sd, strict=False) if not only_model else self.model.load_state_dict(
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LatentDiffusion:
        size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([320, 1280]) from checkpoint, the shape in current model is torch.Size([320, 768])...............
..............
..........
) from checkpoint, the shape in current model is torch.Size([320, 768]).
        size mismatch for model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([320, 1280]) from checkpoint, the shape in current model is torch.Size([320, 768]).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 826, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

**Comment by inspire-boy** [comment]
> > 如果你想使用拥抱脸的概念，你必须遵循他们的 colab / guide。这个 repo 不支持拥抱脸的概念。
> > 如果您确实使用此 repo，只需将您的图像放在一个文件夹中，例如：/home/inspire-boy/my_images/ 然后在运行脚本时使用`--data_root /home/inspire-boy/my_images/`
> 
> Do you now this why this error appears?
> 
> python main.py --base configs/stable-diffusion/v1-finetune.yaml -t --actual_resume "models/ldm/text2img-large/model.ckpt" -n "liangbox" --data_root ../liangbox --init_word "box" --placeholder_tokens "liangbox"
> 
> output:
> 
> Global seed set to 23 Loading model from models/ldm/text2img-large/model.ckpt LatentDiffusion: Running in eps-prediction mode DiffusionWrapper has 859.52 M params. making attention of type 'vanilla' with 512 in_channels Working with z of shape (1, 4, 64, 64) = 16384 dimensions. making attention of type 'vanilla' with 512 in_channels Some weights of the model checkpoint at openai/clip-vit-large-patch14 were not used when initializing CLIPTextModel: ['vision_model.encoder.layers.23.self_attn.out_proj.bias', 'vision_model.encoder.layers.0.self_attn.out_proj.weight', 'vision_model.encoder.layers.5.mlp.fc2.weight', 'visual_projection.weight', 'vision_model.encoder.layers.1.mlp.fc1.bias', 'vision_model.encoder.layers.9.mlp.fc1.bias', 'vision_model.encoder.layers.4.self_attn.k_proj.bias', 'vision_model.encoder.layers.17.self_attn.v_proj.bias',...................... ............... ............
> 
> * This IS expected if you are initializing CLIPTextModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> * This IS NOT expected if you are initializing CLIPTextModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
>   Traceback (most recent call last):
>   File "main.py", line 614, in 
>   model = load_model_from_config(config, opt.actual_resume)
>   File "main.py", line 29, in load_model_from_config
>   model = instantiate_from_config(config.model)
>   File "/root/textual_inversion/ldm/util.py", line 85, in instantiate_from_config
>   return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
>   File "/root/textual_inversion/ldm/models/diffusion/ddpm.py", line 481, in **init**
>   self.init_from_ckpt(ckpt_path, ignore_keys)
>   File "/root/textual_inversion/ldm/models/diffusion/ddpm.py", line 205, in init_from_ckpt
>   missing, unexpected = self.load_state_dict(sd, strict=False) if not only_model else self.model.load_state_dict(
>   File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
>   raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
>   RuntimeError: Error(s) in loading state_dict for LatentDiffusion:
>   size mismatch for model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([320, 1280]) from checkpoint, the shape in current model is torch.Size([320, 768])...............
>   ..............
>   ..........
>   ) from checkpoint, the shape in current model is torch.Size([320, 768]).
>   size mismatch for model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([320, 1280]) from checkpoint, the shape in current model is torch.Size([320, 768]).
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "main.py", line 826, in if trainer.global_rank == 0: NameError: name 'trainer' is not defined

Thanks!This is solved:
1、I leave --gpus item(shhold be --gpus 0)
2、 font error, solved by: apt install fonts-dejavu-core

**Comment by rinongal** [comment]
Sounds good! Is everything resolved then? If so, please close the issue!

**Comment by inspire-boy** [comment]
Okay!
