### ISSUE TITLE
Multi-gpu?

### ISSUE THREAD

**Issue by dboshardy** [rinongal/textual_inversion#69]
My pytorch isn't the greatest.  I see that you can pass in the gpu ids via a command line flag, but I don't see that info used anywhere in the code base.  How is that setting used and where?

**Comment by rinongal** [comment]
It's a pytorch lightning parameter. It is added to the parser by pytorch-lightning's `Trainer.add_argparse_args()` method (in main.py) and is passed to the training module itself as part of the `trainer_opt` variable.

You can see https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html for some details, though it's a bit convoluted.

**Comment by rinongal** [comment]
I'm closing this as resolved. Feel free to reopen if you need more help.
