### ISSUE TITLE
Process sometimes gets stuck repeatedly running DDIM sampler and creating outputs in images/val (not images/train)

### ISSUE THREAD

**Issue by CodeExplode** [rinongal/textual_inversion#72]
Hi, I'm running the textual inversion code from lstein's repo (from the start of the month) which I think was copied from here, though it's possible that some changes there caused this, so am just wondering if there's any obvious reason to the author why this might happen.

Sometimes the process will get stuck on a global step and keeps running DDIM sampler for hours without writing any checkpoints. Output images start getting created in images/val/ instead of images/train/ (which they were getting created in up until that point).

I've just encountered it twice in a row on exactly global step 1500 both times (the second time I resumed from the checkpoint saved when manually cancelling the first. It trained for another 1500 steps, then ran into this problem). Previously the only times I'd noticed this was after increasing accumulate_grad_batches so thought it was related, but it's now set to 1.

It seems there's probably some obvious reason this might happen, and why the val output folder might start getting used at 1500 steps, so before I went digging too far I thought I'd ask. Early on there's a few errors which have never seemed to cause problems but might be related:

e.g. Some weights of the model checkpoint at openai/clip-vit-large-patch14 were not used when initializing CLIPTextModel (followed by 21,000 characters of weight names)

Unexpected Keys: ['model_ema.decay', 'model_ema.num_updates']

Traceback (most recent call last):
  File "userpath\AppData\Roaming\Python\Python38\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (userpath\AppData\Roaming\Python\Python38\site-packages\tensorboard\compat\__init__.py)
During handling of the above exception, another exception occurred:
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Restored all states from the checkpoint file at logs/Set1a_15v/checkpoints/last.ckpt

However everything proceeds past there and I don't think those are new.

My logs around the time of the loop start look like this (with a lot of Deprecation Warnings about ANTIALIAS pruned). In particular the global step gets stuck but the percentage & counter increase by 1 each time.

Epoch 17:  36%|▎| 57/158 [00:36<01:03,  1.60it/s, loss=0.0715, v_num=0, train/loss_simple_step=0.071, train/loss_vlb_step=0.000234, train/loss_step=0.071, global_step=1399.0, train/loss_simple_epoch=0.104, train/loss_vlb_epoch=0.00128, Epoch 17, global step 1399: val/loss_simple_ema was not in top 1
pop from empty list
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:38<00:00,  5.26it/s]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:38<00:00,  5.26it/s]
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:09<00:00,  2.90it/s]
Epoch 17: 100%|█| 158/158 [03:37<00:00,  1.36s/it, loss=0.156, v_num=0, train/loss_simple_step=0.0226, train/loss_vlb_step=9.03e-5, train/loss_step=0.0226, global_step=1421.0, train/loss_simple_epoch=0.104, train/loss_vlb_epoch=0.00128,Average Epoch time: 217.01 seconds
Average Peak memory 9195.58MiB
Epoch 18:  49%|▍| 78/158 [00:48<00:48,  1.64it/s, loss=0.115, v_num=0, train/loss_simple_step=0.00215, train/loss_vlb_step=1.29e-5, train/loss_step=0.00215, global_step=1499.0, train/loss_simple_epoch=0.115, train/loss_vlb_epoch=0.00089Epoch 18, global step 1499: val/loss_simple_ema was not in top 1
pop from empty list
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:38<00:00,  5.17it/s]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:38<00:00,  5.23it/s]
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:08<00:00,  2.90it/s]
Epoch 18:  50%|▌| 79/158 [02:39<02:37,  1.99s/it, loss=0.115, v_num=0, train/loss_simple_step=0.0404, train/loss_vlb_step=0.000145, train/loss_step=0.0404, global_step=1500.0, train/loss_simple_epoch=0.115, train/loss_vlb_epoch=0.000897pop from empty list                                                                                                                                                                                                   | 0/79 [00:00<?, ?it/s]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:38<00:00,  5.24it/s]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:38<00:00,  5.34it/s]
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:07<00:00,  2.98it/s]
  image = image.resize((scaled_width, scaled_height), Image.ANTIALIAS)████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:07<00:00,  2.99it/s]
Epoch 18:  51%|▌| 81/158 [04:29<04:13,  3.29s/it, loss=0.115, v_num=0, train/loss_simple_step=0.0404, train/loss_vlb_step=0.000145, train/loss_step=0.0404, global_step=1500.0, train/loss_simple_epoch=0.115, train/loss_vlb_epoch=0.000897pop from empty list█▎                                                                                                                                                                                      | 1/79 [01:50<2:23:16, 110.21s/it]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.30it/s]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.36it/s]
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:06<00:00,  2.99it/s]
  image = image.resize((scaled_width, scaled_height), Image.ANTIALIAS)████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:06<00:00,  3.00it/s]
Epoch 18:  52%|▌| 82/158 [06:17<05:45,  4.54s/it, loss=0.115, v_num=0, train/loss_simple_step=0.0404, train/loss_vlb_step=0.000145, train/loss_step=0.0404, global_step=1500.0, train/loss_simple_epoch=0.115, train/loss_vlb_epoch=0.000897pop from empty list███▋                                                                                                                                                                                    | 2/79 [03:37<2:19:33, 108.75s/it]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.36it/s]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.42it/s]
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:06<00:00,  3.00it/s]
  image = image.resize((scaled_width, scaled_height), Image.ANTIALIAS)████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:06<00:00,  3.00it/s]
Epoch 18:  53%|▌| 83/158 [08:04<07:12,  5.77s/it, loss=0.115, v_num=0, train/loss_simple_step=0.0404, train/loss_vlb_step=0.000145, train/loss_step=0.0404, global_step=1500.0, train/loss_simple_epoch=0.115, train/loss_vlb_epoch=0.000897pop from empty list██████                                                                                                                                                                                  | 3/79 [05:25<2:16:54, 108.09s/it]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.35it/s]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.39it/s]
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:06<00:00,  3.00it/s]
  image = image.resize((scaled_width, scaled_height), Image.ANTIALIAS)████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:06<00:00,  3.00it/s]
Epoch 18:  53%|▌| 84/158 [09:51<08:34,  6.96s/it, loss=0.115, v_num=0, train/loss_simple_step=0.0404, train/loss_vlb_step=0.000145, train/loss_step=0.0404, global_step=1500.0, train/loss_simple_epoch=0.115, train/loss_vlb_epoch=0.000897pop from empty list████████▎                                                                                                                                                                               | 4/79 [07:12<2:14:37, 107.70s/it]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.35it/s]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.42it/s]
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:07<00:00,  2.98it/s]
  image = image.resize((scaled_width, scaled_height), Image.ANTIALIAS)████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:07<00:00,  3.00it/s]
Epoch 18:  54%|▌| 85/158 [11:39<09:53,  8.13s/it, loss=0.115, v_num=0, train/loss_simple_step=0.0404, train/loss_vlb_step=0.000145, train/loss_step=0.0404, global_step=1500.0, train/loss_simple_epoch=0.115, train/loss_vlb_epoch=0.000897pop from empty list██████████▋                                                                                                                                                                             | 5/79 [09:00<2:12:56, 107.79s/it]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:38<00:00,  5.16it/s]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:38<00:00,  5.41it/s]
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:08<00:00,  2.92it/s]
  image = image.resize((scaled_width, scaled_height), Image.ANTIALIAS)████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:08<00:00,  2.85it/s]
Epoch 18:  54%|▌| 86/158 [13:30<11:10,  9.31s/it, loss=0.115, v_num=0, train/loss_simple_step=0.0404, train/loss_vlb_step=0.000145, train/loss_step=0.0404, global_step=1500.0, train/loss_simple_epoch=0.115, train/loss_vlb_epoch=0.000897pop from empty list█████████████                                                                                                                                                                           | 6/79 [10:51<2:12:22, 108.80s/it]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.34it/s]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.41it/s]
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:07<00:00,  2.98it/s]
  image = image.resize((scaled_width, scaled_height), Image.ANTIALIAS)████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:07<00:00,  2.99it/s]
Epoch 18:  55%|▌| 87/158 [15:18<12:20, 10.44s/it, loss=0.115, v_num=0, train/loss_simple_step=0.0404, train/loss_vlb_step=0.000145, train/loss_step=0.0404, global_step=1500.0, train/loss_simple_epoch=0.115, train/loss_vlb_epoch=0.000897pop from empty list███████████████▍                                                                                                                                                                        | 7/79 [12:39<2:10:15, 108.55s/it]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.34it/s]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.41it/s]
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:07<00:00,  2.98it/s]
  image = image.resize((scaled_width, scaled_height), Image.ANTIALIAS)████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:07<00:00,  2.99it/s]
Epoch 18:  56%|▌| 88/158 [17:06<13:27, 11.53s/it, loss=0.115, v_num=0, train/loss_simple_step=0.0404, train/loss_vlb_step=0.000145, train/loss_step=0.0404, global_step=1500.0, train/loss_simple_epoch=0.115, train/loss_vlb_epoch=0.000897pop from empty list█████████████████▋                                                                                                                                                                      | 8/79 [14:27<2:08:13, 108.36s/it]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.32it/s]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:37<00:00,  5.42it/s]
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:07<00:00,  2.98it/s]
  image = image.resize((scaled_width, scaled_height), Image.ANTIALIAS)████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [01:07<00:00,  2.99it/s]
Epoch 18:  56%|▌| 89/158 [18:54<14:29, 12.60s/it, loss=0.115, v_num=0, train/loss_simple_step=0.0404, train/loss_vlb_step=0.000145, train/loss_step=0.0404, global_step=1500.0, train/loss_simple_epoch=0.115, train/loss_vlb_epoch=0.000897pop from empty list████████████████████                                                                                                                                                                    | 9/79 [16:15<2:06:16, 108.24s/it]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler:  34%|██████████████████████████████████████████████████████████████▌                                                                                                                         | 68/200 [00:12<00:25,  5.24it/s]
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")██▌                                                                                                                         | 68/200 [00:12<00:24,  5.42it/s]
Summoning checkpoint.

**Comment by CodeExplode** [comment]
Sorry I see now that this is creating one validation image per sample data image, and because I use huge datasets it's going to take a long time. I'm not sure why this never triggered in most of my times running this code even for entire nights, but in some inversions is triggered within an hour or two.

**Comment by rinongal** [comment]
The DDIM sampling results should happen according to your batch size, not according to the dataset size. I'll have a look.
If your set is very big, you can reduce the repeats parameter in the config. Just ensure that your [batch size * accumulation steps * number of gpus] is smaller than your [dataset size * repeats].

**Comment by CodeExplode** [comment]
It's possible that it's something unique to the repo I'm using, so don't want to push you to go searching too hard. I was just hoping the reason for a 'val' image folder being created (instead of 'train') partway through the process might have an immediately known likely reason.

**Comment by rinongal** [comment]
Pretty much all the logging and validation code (besides for the scaled_samples output) is baseline LDM, and I didn't poke it at that level. It's certainly possible there's some issue cropping up there.

Since it's the same code, you might be able to find someone with similar issues on their original repo? I'll have a brief scan either way, maybe I can find something quickly.

**Comment by CodeExplode** [comment]
Since nobody else seems to have encountered this, it was probably related to my repo or settings.

**Comment by TaleirOfDeynai** [comment]
I've been encountering this.

The only thing I can add about my environment is that I'm running on an AMD ROCm system, and ROCm does not work with Anaconda very well, so I am running on the global Python installation and have been having to balance dependency versions for PyTorch and friends that makes all these various tools/libraries relatively happy.

All these PyTorch-Lightning deprecations that you've not been keeping up on...  Kinda a pain in my butt.  I'm running the latest version of PyTorch-Lightning that happens to still support the now-deceased `TestTubeLogger`, which was 1.6.5.  I cannot tell you if this issue happens when using the officially prescribed version of PyTorch-Lightning in the `environment.yaml`, since using that one breaks other software in my Stable Diffusion pipeline.

I can add that I have observed that this issue seems to happen whenever the end of an epoch is reached just as a training image would be logged.  There are those few extra steps at the end of the epoch where the validation `DataLoader` kicks off to prepare for the next epoch (I assume) and I guess if the `ImageLogger` is added on the same step as that starts, it can accidentally get tied together with it and starts spitting out images into the `val` folder until the `DataLoader` has finished its work.

I thought that was intentional at first, but it was weird how inconsistent it was to trigger and how there appeared to be no setting to control the behavior.  I guess it was actually an unintended interaction between modules loaded into the same processing pipeline.

Anyways, reproduction is to tune:

- `data.params.batch_size`
- `data.params.train.params.repeats`
- `lightning.callbacks.params.batch_frequency`
- The number of images in the training set.

...so this coincidence is forced.  You can use the same logic to workaround the issue, making sure they're all out-of-sync for at least as long your `max_steps` configuration is set to.

**Comment by TaleirOfDeynai** [comment]
I'll add a specific test setup, rather than providing something vague.

- Grab 20 images for a training set, 10 will end up in the `train` set and 10 in the `val` set.
- The `stable-diffusion/v1-finetune.yaml` file should already be setup so that:
  - `data.params.batch_size` is `2`
  - `data.params.train.params.repeats` is `100`
  - `lightning.callbacks.params.batch_frequency` is `500`
- Begin training using the `stable-diffusion/v1-finetune.yaml` configuration.

10 images times 100 repeats divided by a batch of 2 is 500 iterations, and an image is logged every 500 iterations, so this should cause the bug to manifest every epoch, whenever the `global_step` is a multiple of 500; more or less the worst case scenario.

When it occurs, it should generate and log 10 sets of images into the `images/val` folder in the same manner it would the `images/train` folder, one for every image in the `val` set.

I believe it does this because `global_step` does not advance during the steps involving the validation `DataLoader`, so it's kind of like the same `global_step` repeats until every image of the `val` set has been loaded.  And because the `global_step` is a multiple of `500` throughout this process, it will always add the `ImageLogger` into the pipeline and generate an image set.

**Comment by TaleirOfDeynai** [comment]
Ooohhh...  I just tried setting `accumulate_grad_batches` to `4` and now I'm generating 4 image sets into `images/train` when the `global_step` hits a multiple of `lightning.callbacks.params.batch_frequency`  ...because it's doing four iterations all in the same `global_step`, invoking the `ImageLogger` every time!

That explains the behavior reported in [this comment](https://github.com/rinongal/textual_inversion/issues/35#issuecomment-1245180138) from before, "then 4 rounds of testing are done in a row."  I doubt this is intentional either.

It sounds like you really just need to track the last `global_step` an image was logged for and skip all that if that value is equal to `global_step`; that would probably solve almost all these problems.  I'd only look out to make sure it never logs into `images/val` if it coincides with the `DataLoader` iterations at the end of the epoch.

**Comment by CodeExplode** [comment]
Awesome thanks for figuring that out. Once I get back to TI it seems definitely worth looking into all the various updates and optimizations which people have come up with, which will hopefully be a quick and easy way around problems like this. I noticed in the Automatic repo commits for textual inversion implementation that there was a change made to prevent logging from 'blowing up' if it happens at the end of an epoch, which might be the same issue.
