### ISSUE TITLE
Reconstruction loss does not change, although samples improving

### ISSUE THREAD

**Issue by RealAntonVoronov** [rinongal/textual_inversion#82]
Hello. Thank you for your great work. I was trying to use your code and obtained satisfying results, thank you very much again. However when I was trying to analyze the training procedure I have observed, that reconstruction loss actually fluctuates over the same value during the whole training, while the quality of intermediate samples_scaled constantly grows. 

I was wondering if it is an expected behaviour? If yes, is there any explanation to it. And if no, what might be the cause?

step-200 of training:
![step-200 of training](https://user-images.githubusercontent.com/22032628/191286847-d16b83de-c347-4f3a-b64b-2f4f924b435e.png)

step-5000 of training:
![step-5000 of training](https://user-images.githubusercontent.com/22032628/191287005-246971fd-320c-4530-98ea-9f0da3db9900.png)

examples_of_input:
![examples_of_input](https://user-images.githubusercontent.com/22032628/191287121-3d8edfb7-da8e-481a-a692-84e26187b038.png)
![loss behaviour](https://user-images.githubusercontent.com/22032628/191287283-0364d076-2db2-4aaa-bed6-43f8d986bfae.png)

**Comment by rinongal** [comment]
Hi Anton,

We never actually bothered looking at the loss landscape here, so I wouldn't say this is expected.

With that said, if you look at the unscaled samples, you'll see that it tends to produce very bad results without high CFG scaling, and the loss is computed on such unscaled outputs. What you're seeing might just be the noisy and un-improving nature of these outputs. 

How come the scaled outputs still improve? One possibility is that the unscaled results just represent a very wide distribution around a 'good' mean. This mean is improving, but when you're looking at the loss, the noise vastly overwhelms the improvements. Using high CFG scales lets you reduce the variance and get closer to this mean.

With that said, this is all speculation and if you're genuinely curious, you should likely run some experiments to see if this holds up.

**Comment by RealAntonVoronov** [comment]
Okey, thank you very much for your response. It has actually improved my understanding of the matter.
