### ISSUE TITLE
placeholder_tokens and placeholder_strings

### ISSUE THREAD

**Issue by tmuskal** [rinongal/textual_inversion#85]
in [main.py](https://github.com/rinongal/textual_inversion/blob/8f820990db3e0a16687f63588b931a3bf20f2a88/main.py#L608), the code is referring to the *placeholder_tokens* param (main is the only place it is referenced), while the model refers to *placeholder_strings*.

it seem that currently the training process ignores the *--placeholder_tokens* cmd-line argument.

Am I missing something, or is it simply a typo?

Thanks and keep up the amazing work.

**Comment by rinongal** [comment]
That's a bug alright. The config file is using placeholder_strings as expected, so you can either fix the parameter name here or modify the placeholders in the config. I'll fix this either way.
