### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'load'

### ISSUE THREAD

**Issue by Josh-Yang95** [rinongal/textual_inversion#86]
I'm facing the following error

![Screenshot from 2022-09-25 15-23-56](https://user-images.githubusercontent.com/70742598/192131573-722b53df-6a75-42f5-8d6d-2895e1e010c0.png)

I trained the model and merged embedding successfully. 

I used the correct command, but I got the above error when generating images with txt2img.py 

What should I do with this?

**Comment by rinongal** [comment]
What config are you loading? Are you using this version of the repo or some fork? Can you paste your full command?

**Comment by Josh-Yang95** [comment]
1. What config are you loading?
-> I used v1-finetune_unfrozen_style.yaml for training and v1-inference.yaml for inference in stable-diffusion folder.

2. Are you using this version of the repo or some fork?
-> Yes

3. Can you paste your full command?
-> python scripts/txt2img.py --ddim_eta 0.0 --n_samples 8 --n_iter 1 --scale 10 --ckpt /my/checkpoints/last.ckpt --prompt "Adorable corgi in the style of *" --ddim_steps 50 --embedding_path /my/checkpoints/embeddings_gs-5999.pt

Is there anything I missed?

**Comment by rinongal** [comment]
So first of all, you appear to be using a stable diffusion config along with the LDM inference code. You should use stable_txt2img.py.

Secondly, we don't have a v1-finetune_unfrozen_style.yaml. Is it just a modification of finetune_unfrozen to use style prompts? Can you double check the size of your last.ckpt file to make sure you're getting a fine-tuned output and not just the 'empty' model checkpoints that the regular inversion produces?

**Comment by Josh-Yang95** [comment]
First, You should use stable_txt2img.py
-> The same error occurred... 

Second, it is the style prompt config for my convenience, but I only fixed the dataloader file. I double-checked the size of the model. The model size is 12G and the embedding size is 5KB. Is it right?

Thanks,

**Comment by rinongal** [comment]
Those sizes appear more or less correct, yes. I'd expect the embedding file to be a bit smaller (~3-4kb) but that is not what's causing your issue.

Do you happen to have more than one version of stable diffusion / LDM on your machine? Can you try explicitly adding the repo to your pythonpath (e.g. by prefixing your command with `PYTHONPATH=/path/to/textual_inversion/` and checking if the problem persists?

**Comment by Josh-Yang95** [comment]
wow... it worked finally when prefixing my command with the absolute path.

Now I can jump into concept art through your amazing repo.

Thanks very much.

**Comment by rinongal** [comment]
Happy to help. Python was likely finding another SD repo on your machine and using the files form there instead.
Closing as resolved. Feel free to re-open if you need more help.
