### ISSUE TITLE
dual 12gb gpu gets CUDA OOM, single works

### ISSUE THREAD

**Issue by ryanrussell** [rinongal/textual_inversion#94]
# Description
Using a single 12g GPU works for training a style; however, trying to use 2x12g GPU gets OOM **if** GPU 0 has 11g instead of 12g available

### Details

```bash
# Generic command
python main.py --no-test --base ...yaml -t --actual_resume ./models/ldm/text2img-large/model.ckpt -n ...  --gpus 0,1  --data_root ... --init_word ...
```

GPU 0 has ~1gb dedicated to the GUI(ubuntu desktop). This is enough to fail the model when trying to parallelize across two GPUs.

```bash
Running on GPUs 0,1
Loading model from ./models/ldm/text2img-large/model.ckpt
Global seed set to 23
initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 872.30 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Restored from ./models/ldm/text2img-large/model.ckpt with 0 missing and 2 unexpected keys
Unexpected Keys: ['model_ema.decay', 'model_ema.num_updates']
Traceback (most recent call last):
  File "/home/ryan/lab/textual_inversion/main.py", line 613, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "/home/ryan/lab/textual_inversion/main.py", line 38, in load_model_from_config
    model.cuda()
  File "/home/ryan/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 128, in cuda
    return super().cuda(device=device)
  File "/home/ryan/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 680, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/ryan/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/ryan/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/ryan/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/home/ryan/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/home/ryan/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 680, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 0; 11.78 GiB total capacity; 1.93 GiB already allocated; 118.94 MiB free; 1.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

![image](https://user-images.githubusercontent.com/523300/193274716-f90666de-397c-42ef-8bd9-a60b28b7eaac.png)

#### The same command with `--gpus 1,` will succeed training as expected.
It seems to peak around 11,039mb ... which explains why it fails on `GPU 0` in this example.

#### Questions
Is there a small tweak I'm missing? Possibly a way to make it bind to a specific GPU(GPU 1 in this example) for the init? 

Or is 12G just the absolute minimum, and this is expected in a scenario like this?

Greatly appreciate any wisdom you can share!

**Comment by CodeExplode** [comment]
> Or is 12G just the absolute minimum, and this is expected in a scenario like this?

I've been able to run it (with stable diffusion) on a single 12gb rtx 3060 which is also running windows (and occasionally youtube videos etc). It was a different repo but I think they copied the code exactly from here.

My changes were to set batch size to 1 and num workers to 2, in v1-finetune.yaml > data > params, and later I added accumulate_grad_batches: 4 to the last line of the yaml file in the lightning > trainer section, to try to help with the reduced batch size.

**Comment by rinongal** [comment]
@ryanrussell How willing are you to tinker with code? You could possibly implement the improved cross attention mechanism used in the newer 'dreambooth' forks. That seems to significantly reduce memory requirements.

**Comment by ryanrussell** [comment]
@rinongal 

> @ryanrussell How willing are you to tinker with code? 

Very. 

Are you referencing the `xformers` mod that (I believe) originated with the PR from @MatthieuTPHR [this diffusers pr](https://github.com/huggingface/diffusers/pull/532)?

Do these types of PR's belong in your repo or in a fork? Are extra dependencies welcomed?

Is the intent in `textual_inversion` to stay true to the original arxiv pub or to evolve?

**Comment by rinongal** [comment]
I did have the xformers mod in mind, yes.

Intent is to stay mostly true to the scope of the original paper. 

I don't mind adding optimizations that are orthogonal to the current functionality, so optimizing memory requirements / run times is more than fine, as long as there's no harm to actual results *or* it's toggleable (so others still have the option to reasonably reproduce our initial results).

PRs in the repo are fine.
Extra dependencies are fine, so long as it's not something that requires some messy manual installation.

**Comment by ryanrussell** [comment]
Before trying to materially change the implementation, I've been trying to do some more due diligence to understand what is happening. 

As of now, running the process using EITHER GPU 0 or 1 works.

Works: 
- --gpus "0,"
- --gpus "1,"

Does not work:
- --gpus "0,1,"
- 2 separate processes using each GPU (GPU 0 resources still get used for the GPU 1 job)

It appears there's something in/around `load_model_from_config()` consumes GPU 0 resources regardless of the CLI param. There are various nested imports in conditional statements that I'm still wrapping my head around that may be culprits.

When run with two GPU's or with GPU 1, the memory demands on GPU 0 spike before/around the call to `model = load_model_from_config(config, opt.actual_resume)`

Below is a screenshot right around that handoff when running using `--gpus "1,"` -- Notice how the GPU 0 memory jumped to ~8gb even though it's not supposed to be used:

![image](https://user-images.githubusercontent.com/523300/193484703-d8207d9d-8656-4e86-be00-78c6c4a10ed0.png)

This is around the stdout:
```bash
Global seed set to 23
initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
```

As soon as the training begins on GPU 1, the GPU 0 memory goes back down to ~2gb. When I force-kill the training on GPU 1, GPU 0 memory goes back to ~690mb as of this run.

### Summary
When assigning GPU 1, something is still using GPU 0 resources peaking at ~8gb right before training beginds, and ~1.3gb during training.

@rinongal -- I'm going to keep looking into this, if something out of my description seems obvious to you what is going on, would love any insights you may have.

**Comment by ryanrussell** [comment]
#### Solution:
There are various `model.cuda()` calls, which defaults to GPU 0. 

The most offensive is in `load_model_from_config()` in `main.py`

This will have zero effect on machines with only one GPU.

It may, however, cause strange side effects on multi-gpu machines if the memory is near-capacity. Likely would not OOM in a 2x24G VRAM GPU environment, but fails consistently on a 2x12G GPU config.

Either of these seem to work well for me:
1. Just remove the `model.cuda()` calls
2. Bind the `model.cuda()` to your CLI GPU(can also cause OOM...) `model.to(torch.device('cuda:[id]'))`

```python
    # model.cuda()
    
    # Optional assignment to your preferred GPU like
    model.to(torch.device('cuda:1'))
```

Updating these references allows me to train with multiple GPU's and/or multiple processes with single GPU's

@rinongal -- do you have opinions on which you think would be better based on your intent?

If you like, I can try to touch up the references to `model.cuda()` to align them with the CLI param.

**Comment by rinongal** [comment]
Cheers for investigating this!

If removing model.cuda() from load_model_from_config() works, I'd do that. It keeps it closest to the original LDM implementation and lets Pytorch Lightning handle most movements to the GPU.

**Comment by ryanrussell** [comment]
Sent a PR with notes just removing that single `model.cuda()` call -- that gets us to working on 2x12GB GPU's.

The `xformers` and other `model.cuda()` calls would definitely improve memory requirements further... this seems like a good middle-ground that solve the initial problem for almost no effort. :+1:

**Comment by rinongal** [comment]
Merged. If it solves your issue, it's good enough for now :)
Closing as resolved. Let me know if you need further help.
